# Generated by Django 2.2.4 on 2022-12-22 19:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_comment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pw_confirm',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.BinaryField(max_length=255),
        ),
    ]
