# Generated by Django 4.1.5 on 2023-01-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0002_pie_voted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pie',
            name='voted_by',
        ),
        migrations.AddField(
            model_name='user',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
