# Generated by Django 4.1.5 on 2023-01-17 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examapp', '0003_remove_pie_voted_by_user_voted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='voted',
        ),
        migrations.AddField(
            model_name='pie',
            name='voted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pie_voted', to='examapp.user'),
        ),
    ]
